## debug related
seed: null
verbose: true

## pybullet related
viewer: true
lock: true
simulate: false
teleport: false
drive: true
cfree: false
time_step: 5e-3
camera: true
segment: false
monitoring: false

## data collection mode
parallel: false
n_data: 3


robot:
  robot_name: 'feg'
  builder_name: 'build_robot_from_args'
  builder_kwargs:
    ## x, y, z joint limits for base motion planning
    custom_limits: [[0, -3, 0], [3, 3, 3]]
    initial_q: [2, 0, 0.7, 0, -1.57, 0]
    spawn_range:
    ## variations in initial base conf in generated worlds
      x: [2.5, 5.8]
      y: [2, 3.5]
      z: [0.5, 1.9]


world:
  ## method 1: use pre-specified builder inside world_builder/builders,
  ##         followed by builder specific arguments
  builder_name: 'test_feg_kitchen_mini'
  builder_kwargs:
    movable_categories: ['edible']
    goal_predicates: ['holding', 'on', 'in']


data:
  out_dir: '../outputs/test_feg_kitchen_mini/'
  save_failed_plans: true
  save_log: true
  save_commands: true
  images:
    save_rgb: true
    save_depth: false
  resolution: [1280, 720]
  fx: 800
  ## {name: pose} pairs
  cameras:
    ## pose format 1: (point, quaternion)
    front: [[6.84, 2.9, 1.3], [0.5, 0.5, -0.5, -0.5]]
    ## pose format 2: (camera_point, target_point)
    top: [[2, 4, 3], [0, 4, 1]]
    ## pose format 3: (object_name, delta_to_target)
    zoomin1: ['minifridge', [2, 0, 2]]


## configuration for PDDLStream
planner:
  timeout: 300
  domain_pddl: 'pddl_domains/feg_kitchen.pddl'
  stream_pddl: 'pddl_domains/feg_stream_kitchen.pddl'
  diverse: false
  downward_time: 1
  dataset: false