## all relative paths in this file has pybullet_planning as the root dir

## debug related
seed: null
verbose: true

## configuration for PDDLStream
planner:
  visualization: false
  scene_only: false
  use_heuristic_fc: false
  dataset_mode: true
  downward_time: 3
  evaluation_time: 30
  stream_planning_timeout: 30
  total_planning_timeout: 60
  max_plans: 10
  max_solutions: 1
  max_skeletons: 300
  max_evaluation_plans: 300
  log_failures: false

## specify the TAMP problem with preconfigured scene layout & robot
problem:
  problem: 'test_full_kitchen'
  goal_variations: [2]
  domain_pddl: 'pddl_domains/pr2_domain_pigi.pddl'
  stream_pddl: 'pddl_domains/pr2_stream_pigi.pddl'
  use_skeleton_constraints: false
  use_subgoal_constraints: false
  use_rel_pose: false
  preview_plan: false
  preview_scene: false

## outputs to generate
data:
  exp_dir: '../outputs'
  exp_subdir: 'piginet_data'
  exp_name: 'default'
  record_problem: true
  record_mp4: false
  save_testcase: false

robot:
  robot_name: 'pr2'
  draw_base_limits: true
  dual_arm: false
  self_collisions: false

## planning stream related
streams:
  debug: true
  cfree: false
  teleport: false
  disable_movable_collision: false
  disable_base_collision: false
  top_grasp_tolerance: 1.58
  ir_max_attempts: 60

## pybullet related
sim:
  window_width: 1080
  window_height: 675
#  window_width: 1980
#  window_height: 1238
  viewer: true
  lock: true
  simulate: false
  drive: false
  time_step: 0.05
  camera: false
  segment: false
  monitoring: false
  show_object_names: true